name: Check

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ github.token }}
          version: 2.5.2
          args: --config-path stylua.toml --check lib tests

  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}

      - name: Map source
        run: rojo sourcemap dev.project.json -o sourcemap.json

      - name: Map environment
        run: |
          mkdir dist
          curl -L https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/refs/heads/main/scripts/globalTypes.d.luau -o dist/roblox.d.luau
          curl -L https://gist.githubusercontent.com/ernisto/3b0e3513700e20ccf8011efc77de234e/raw/3b140bcb8d6d7953d628bb3f3b6cf49d9784fbaf/vector.d.luau -o dist/vector.d.luau

      - name: Lint
        run: >
          luau-lsp analyze
          --platform roblox
          --base-luaurc .luaurc
          --sourcemap sourcemap.json
          --defs dist/roblox.d.luau
          --defs dist/vector.d.luau
          lib tests/roblox

  automated-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}

      - name: Run tests
        run: lute test tests/lute
