name: Release
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  publish_wally:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}

      - run: wally login --token "$WALLY_TOKEN"
        env:
          WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}
          GH_TOKEN: ${{ github.token }}

      - name: Sync wally version
        run: lute run scripts/bump_version

      - name: Publish wally
        run: wally publish

  release_file:
    runs-on: ubuntu-latest
    needs: [check]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}

      - name: Build rbxm
        run: rojo build default.project.json -o defnet.rbxm

      - name: Upload rbxm
        if: ${{github.event.release.tag_name}}
        run: gh release upload ${{github.event.release.tag_name}} defnet.rbxm
        env:
          GH_TOKEN: ${{ github.token }}
